/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Wireframe(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/maskWireframe.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.04, 0]}>
        <group position={[-0.03, 0.65, 0]} scale={1.41}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8001.geometry}
            material={materials['Material.003']}
            scale={1.09}
          >
            <meshStandardMaterial
              color="#80FFFF"
              opacity={0.2}
              transparent={true}
            />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/maskWireframe.glb')
